version: '3'
services:
  postgres:
    image: postgres:10.16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
